/**
 *
 * @author cheryl
 */
public class View extends javax.swing.JFrame {
   
    /**
     * Creates new form ElevatorStatus
     */
    public View() {
        initComponents();
        this.setVisible(true);
        
    }
    public void exitElevatorView(){
        System.exit(0);
    }
    public void updateAll(int floor, int pass, boolean goingUp){
        if (stateChangeFloor(floor)) setFloor(floor);
        if (stateChangePassenger(pass)) setPassenger(pass);
        if (stateChangeDirection(goingUp)) setDirectionChange();
    }
    public void setFloor(int newFloor){
        jFloor.setText(Integer.toString(newFloor));
    }
    public void setPassenger(int newPass){
        jNumPass.setText(Integer.toString(newPass));
    }
    public void setDirectionChange(){
        if(jDirection.getText().equals("UP")) jDirection.setText("DOWN");
        else jDirection.setText("UP");
    }
    public boolean stateChangeFloor(int cFloor){
        int floor = Integer.parseInt(jFloor.getText());
        return cFloor != floor;
    }
    public boolean stateChangePassenger(int cPass){
        int pass = Integer.parseInt(jNumPass.getText());
        return cPass != pass;
    }
    public boolean stateChangeDirection(boolean cGoingUp){
        boolean goingUp = false;
        if(jDirection.getText().equals("UP")) goingUp = true;
        return cGoingUp != goingUp;
    }
    /**
     * This method is called from within the constructor to initialize form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jElevatorStatus = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelFloor = new javax.swing.JLabel();
        jLabelNumPass = new javax.swing.JLabel();
        jLabelDirection = new javax.swing.JLabel();
        jFloor = new javax.swing.JLabel();
        jNumPass = new javax.swing.JLabel();
        jDirection = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jElevatorStatus.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jElevatorStatus.setText("Elevator Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jElevatorStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jElevatorStatus)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabelFloor.setText("Current Floor");

        jLabelNumPass.setText("Number of Passengers");

        jLabelDirection.setText("Direction");

        jFloor.setText("1");

        jNumPass.setText("0");

        jDirection.setText("UP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFloor)
                    .addComponent(jLabelNumPass)
                    .addComponent(jLabelDirection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDirection)
                    .addComponent(jNumPass)
                    .addComponent(jFloor))
                .addGap(97, 97, 97))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFloor)
                    .addComponent(jFloor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumPass)
                    .addComponent(jNumPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDirection)
                    .addComponent(jDirection))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param args
     */
    
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    */
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
   //     java.awt.EventQueue.invokeLater(new Runnable() {
   //         @Override
   //         public void run() {
   //             new View().setVisible(true);
   //         }
   //     });
   // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDirection;
    private javax.swing.JLabel jElevatorStatus;
    private javax.swing.JLabel jFloor;
    private javax.swing.JLabel jLabelDirection;
    private javax.swing.JLabel jLabelFloor;
    private javax.swing.JLabel jLabelNumPass;
    private javax.swing.JLabel jNumPass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
